;             
CREATE USER IF NOT EXISTS "SA" SALT '67d459e4b965afcf' HASH 'eb5f9c1f6650028c5f9da5fde0533248ada805385746847e94ec26fe99bed9d0' ADMIN;         
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 36;  
CREATE CACHED TABLE "PUBLIC"."CUSTOMER"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");     
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;
INSERT INTO "PUBLIC"."CUSTOMER" VALUES
(33, 'Sebastian'),
(34, 'Danny'),
(35, 'Roger');    
CREATE CACHED TABLE "PUBLIC"."PURCHASE"(
    "ID" BIGINT NOT NULL,
    "PRICE" DOUBLE NOT NULL,
    "PURCHASE_DATE" TIMESTAMP NOT NULL,
    "CUSTOMER_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."PURCHASE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE;
ALTER TABLE "PUBLIC"."PURCHASE" ADD CONSTRAINT "PUBLIC"."FK2PEHE23HWDCYQL94C531RBF70" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;
